### ISSUE TITLE
Items from Stef's Jun26 post-launch review

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/website-new#45]
Some things that came up as I clicked around newly-released website.

## Broken things

- Image not displaying in blog post [Hello Quarto! A Quarto Chat with NASA Openscapes, co-hosted with R-Ladies Santa Barbara](https://openscapes.org/blog/2022-06-22-hello-quarto/): `img src=“/img/blog/quarto-nasa-earthdata-cloud-cookbook.png ...`
- Update: this was fixed in site preview when I pushed files from building site: ~Thumbnail img does not appear for many posts on [blog listing page](https://openscapes.org/blog.html). Example posts:~
  - ~[NASA Openscapes: efforts to support end users in the journey to the cloud](https://openscapes.org/blog/2022-12-12-nasa-se-tim/)~
  - ~[Openscapes Champions Program: Fall 2021 Updates](https://openscapes.org/blog/2021-11-03-champions-fall-cohorts-2021/)~  
- Warning on building site locally; several instances:
	`[146/160] events/2022-10-04-noaa-swfsc-pifsc-fall/index.qmd`
	`[WARNING] Citeproc: citation openscapes not found`
- Page not found: "We’ve added a new [openscapes.org/partners](https://openscapes.org/partners) page" linked from blog post [Openscapes Events Spring 2021](https://openscapes.org/blog/2021-03-04-events-spring-2021/)

## for version 2.0

- could quotes stand out more? [example 1](https://openscapes.org/blog/2023-05-17-mentor-coach/) [example 2](https://openscapes.org/blog/2023-05-17-mentor-coach/). 
![Screenshot 2023-06-26 at 9 24 00 PM](https://github.com/Openscapes/website-new/assets/11927811/30ab447c-9c07-49bc-ad23-311b1562f7bf)

The above examples have quotation marks. [Example 3](https://openscapes.org/blog/2023-01-24-noaa-nmfs-fall/) does not have quotation marks so is even less clear:

<img width="673" alt="Screenshot 2023-06-26 at 9 49 24 PM" src="https://github.com/Openscapes/website-new/assets/11927811/719661a7-cd78-464c-8a2f-ede1e3369a77">

**Comment by samanthacsik** [comment]
@stefaniebutland Thanks for this review! I made updates on the `issue-45` branch and just created a [PR](https://github.com/Openscapes/website-new/pull/47), if you'd like to take a look (the deploy preview looks good though and it seems to have passed all netlify checks). Some notes:

> Image not displaying in blog post [Hello Quarto!](https://openscapes.org/blog/2022-06-22-hello-quarto/)...
-  Not sure why this is randomly happening, but when I've encountered issues with images rendering, I just switch out the html syntax for the `knitr::include_graphics()` syntax (described in [this wiki](https://github.com/Openscapes/website-new/wiki/Adding-images)). I also copied those particular images from the `/img/blog` directory (which was copied over from the blogdown site) into the specific blog post directory (e.g. `/blog/2022-06-22-hello-quarto/`) so that I can just call relative file paths. I ultimately went through all blog posts to fix blockquote styling (see comment a few below this) and fixed any other images that weren't rendering using the same procedure (moving images into blog post directory, using `knitr::include_graphics()` to render them)

>Warning on building site locally; several instances:
[146/160] events/2022-10-04-noaa-swfsc-pifsc-fall/index.qmd
[WARNING] Citeproc: citation openscapes not found
- I'm honestly not sure why this shows up (I've seen it as well) -- the citations seem to be working just fine. I've also seen this show up on my own personal website, despite citations working as expected. So, I think we can ignore these (I know that's not a great response...)

>Page not found: "We’ve added a new [openscapes.org/partners](https://openscapes.org/partners) page" linked from blog post [Openscapes Events Spring 2021](https://openscapes.org/blog/2021-03-04-events-spring-2021/)

- I don't think there ever was a `partners` page on the blogdown site (unless it used to be there and was since deleted? see the [content directory of the blogdown site](https://github.com/Openscapes/website/tree/main/content)). I updated this to: `"We are so grateful for our partners who are helping grow and improve Openscapes. Learn more about them under the [Advisors & Collaborators](team.qmd#advisors-collaborators) section on our [Team page](team.qmd)."` -- let me know if you would prefer to change this to something else

- thanks for catching these! I had to change up the CSS rules for styling blockquotes when we added the speech bubbles on the landing page. See the difference in rendering using the following two syntaxes: 

```
::: {.blockquote-blue}
>*"This is my quote"* **--- Sam Csik, NCEAS**
:::

>*"This is my quote"* **--- Sam Csik, NCEAS**
``` 

which will render them like this: 
<img width="399" alt="Screen Shot 2023-06-27 at 11 50 39 AM" src="https://github.com/Openscapes/website-new/assets/43836046/e4bbfb69-ba8e-4b7f-9220-0250e1eb3d26">

I went through all blog posts and updated them so that they look like the first of the above two examples (with the vertical blue bar, italicized quote, bolded attribution). I also wrote up a short Wiki about blockquotes: [Adding blockquotes](https://github.com/Openscapes/website-new/wiki/Adding-blockquotes)

**Comment by samanthacsik** [comment]
Above items addressed and merged here: https://github.com/Openscapes/website-new/pull/47
